### ISSUE TITLE
libyuv compilation error with Android API 18

### ISSUE THREAD

**Issue by datso** [gotev/pjsip-android-builder#12]
Hello,
I'm trying to build pjsip as described in README, but build fails on libyuv library.

> vagrant@pjsip-android-builder:/pjsip-android-builder$ ./build
> Clear final build folder ...
> Creating config site file for Android ...
> Compile PJSIP for arch armeabi ...
> cp: cannot stat '/pjsip-android-builder/libyuv-android/libs/armeabi/libyuv.so': No such file or directory

[vagrant_up_log.zip](https://github.com/gotev/pjsip-android-builder/files/181956/vagrant_up_log.zip)

BTW, thanks for the work!

**Comment by gotev** [comment]
libyuv android repo has been updated from r1255 to r1580 recently, and that's the cause. Some changes are needed to be able to compile with API 18. Specifically, the bulld has to be made only for non 64 bit builds.

**Comment by gotev** [comment]
Had to disable mips build with Android API 18 due to this compilation error:
```
[mips] SharedLibrary  : libyuv.so
./obj/local/mips/objs/yuv/source/convert.o: In function `libyuv::CopyPlane2(unsigned char const*, int, int, unsigned char*, int, int, int)':
/pjsip-android-builder/libyuv-android/jni/source/convert.cc:212: undefined reference to `CopyRow_MIPS'
./obj/local/mips/objs/yuv/source/planar_functions.o: In function `CopyPlane':
/pjsip-android-builder/libyuv-android/jni/source/planar_functions.cc:66: undefined reference to `CopyRow_MIPS'
/pjsip-android-builder/libyuv-android/jni/source/planar_functions.cc:66: undefined reference to `CopyRow_MIPS'
/pjsip-android-builder/libyuv-android/jni/source/planar_functions.cc:66: undefined reference to `CopyRow_MIPS'
/pjsip-android-builder/libyuv-android/jni/source/planar_functions.cc:66: undefined reference to `CopyRow_MIPS'
./obj/local/mips/objs/yuv/source/planar_functions.o:/pjsip-android-builder/libyuv-android/jni/source/planar_functions.cc:66: more undefined references to `CopyRow_MIPS' follow
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/mips/libyuv.so] Error 1
```
If someone has any clues on how to resolve that, send me a pull request.

**Comment by NeutronStein** [comment]
still not working :(

**Comment by gotev** [comment]
@NeutronStein unless someone has an idea on how to resolve the mentioned error with a patch, it's not going to work.

**Comment by yuvaraj119** [comment]
I am also not able to build for arm64-v8a android architecture. libyuv library dosent have the arm64-v8a. how to update this or any other solution.
