### ISSUE TITLE
Integrating libs into android project

### ISSUE THREAD

**Issue by freemanpolys** [gotev/pjsip-android-builder#13]
Hi,
I've build successfully  the libs with your script (thanks) but I'im having problem for integrating them into my android project (Android Studio 2). 
FYI,  I've copied libs into app/src/main/jniLibs/ .
I added `android.useDeprecatedNdk=true` in gradle.properties.

When I tried to load the library  : ` System.loadLibrary("pjsua2");` I get the error : 

`E/dalvikvm: dlopen("/data/app-lib/com.akakpolabs.mypjsiptest-2/libpjsua2.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1636): could not load library "libopenh264.so" needed by "libpjsua2.so"; caused by load_library(linker.cpp:746): library "libopenh264.so" not found`

I need help

**Comment by gotev** [comment]
You need to copy also libopenh264.so. You can also drop the deprecated NDK directive you've set.

**Comment by freemanpolys** [comment]
the libopenh264.so file is also in the jniLibs .
the jniLibs contains : 

armeabi : 
      - libopenh264.so
      - libpjsua2.so
      - libyuv.so

armeabi-v7a : 
      - libopenh264.so
      - libpjsua2.so
      - libyuv.so

x86 : 
      - libopenh264.so
      - libpjsua2.so
      - libyuv.so

Did I need Android.mk and Application.mk files ?

**Comment by gotev** [comment]
Initialization has a precise flow that has to be followed for the library to work.
```java
private void loadNativeLibraries() {
    try {
        System.loadLibrary("openh264");
        Log.d(TAG, "OpenH264 loaded");
    } catch (UnsatisfiedLinkError error) {
        Log.e(TAG, "Error while loading OpenH264 native library", error);
        throw new RuntimeException(error);
    }

    try {
        System.loadLibrary("yuv");
        Log.d(TAG, "libyuv loaded");
    } catch (UnsatisfiedLinkError error) {
        Log.e(TAG, "Error while loading libyuv native library", error);
        throw new RuntimeException(error);
    }

    try {
        System.loadLibrary("pjsua2");
        Log.d(TAG, "PJSIP pjsua2 loaded");
    } catch (UnsatisfiedLinkError error) {
        Log.e(TAG, "Error while loading PJSIP pjsua2 native library", error);
        throw new RuntimeException(error);
    }
}
```

**Comment by freemanpolys** [comment]
Ok! Thanks for your support.

**Comment by bhupendrasingh4810** [comment]
how can i build pjsip library for android? Please help me
